### ISSUE TITLE
Tweak syntax definition for better colors

### ISSUE THREAD

**Issue by zanuka** [zanuka/dust-buster#14]

**Comment by roydelgado** [comment]
Hello,

Could you please fix the highlighting for JS code in Dust files?

Prior 1.0.4 the highlight for JS syntax was great, now all the JS code is white.

Also, dust syntax highlighting seems to be broken? It was fine before the 1.0.4 update

ie:
//fine
{>"/path/to/dust/file" /}
//this shows up white curly braces white with fuchsia text
{<customBlock}

   //some conditional comments in here
  

//this one below shows fuchsia text with blue text
{/customBlock}

Thank you very much!
