### ISSUE TITLE
Bracket matching fails inside of loop block 

### ISSUE THREAD

**Issue by eltonjuan** [zanuka/dust-buster#22]
Consider the following block of code: 

```
{#items}
       {price}
{/items} 
```

Now, say I want to put the variable `{title}` above price: 

```
{#items}
       {title}
       {price}
{/items} 
```

When I type the first bracket in `{title}` , bracket matching outputs the following: 

```
{#items}
       {
       {price}
       }
{/items} 
```

Instead of what I would expect:

```
{#items}
       {}
       {price}
{/items} 
```

**Comment by zanuka** [comment]
good catch @eltonjuan , fixing now
