### ISSUE TITLE
Syntax highlighting breaks on blocks and inline partials

### ISSUE THREAD

**Issue by rosshamish** [zanuka/dust-buster#31]
The offending behaviour:

![open-close-includes-incorrect-syntax-highlight](https://cloud.githubusercontent.com/assets/1522678/5827305/39bec792-a0c7-11e4-8279-818ce2edc094.png)

Where in the parent partial, there is a `{+header/}` specified.

I'm not sure exactly how the highlighting **should** look. I suppose it should be similar to other elements with open and close like divs, etc.

See this portion, _Blocks and Inline Partials_ in the [dustjs docs](http://akdubya.github.io/dustjs/)

![dustjs-docs-0](https://cloud.githubusercontent.com/assets/1522678/5827265/fa0f06ca-a0c6-11e4-9ecd-330b02a59388.png)

The syntax highlighting breaks when including them with this syntax:

![dustjs-docs-1](https://cloud.githubusercontent.com/assets/1522678/5827294/21b85492-a0c7-11e4-95db-b5e4506d403d.png)

**Comment by rosshamish** [comment]
Here's another good test case

![good-test-case](https://cloud.githubusercontent.com/assets/1522678/5827961/44357170-a0cd-11e4-8183-9e5c49212800.png)

**Comment by zanuka** [comment]
good catch @rosshamish .
fixed in v1.1.7 (https://github.com/zanuka/dust-buster/tree/v1.1.7) 
should be picked up by Package Control within the hour. 
i also added a new completion for inline partials.

**Comment by rosshamish** [comment]
Woohoo! Nice work

![issue31-fixed](https://cloud.githubusercontent.com/assets/1522678/5837880/244522dc-a151-11e4-8eab-0a06ab6430b0.png)

**Comment by zanuka** [comment]
Thanks, glad it fixed the issue.
