### ISSUE TITLE
Completion doesn't seem to work

### ISSUE THREAD

**Issue by raxell** [zanuka/dust-buster#52]
If I write "ds", "db" or any other command and then press TAB nothing is rendered. What's the problem?
Is there a setting for changing the expand key? (e.g. from TAB to CTRL+E)

**Comment by zanuka** [comment]
I just tested and it's working fine for me. My guess is that another Sublime Package you have installed might be conflicting with DustBuster's completion triggers. Are you sure you're on a .dust file when entering the commands and pressing TAB?
